# Generated by Django 3.2.15 on 2022-10-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
    ]
