# Generated by Django 3.2.15 on 2022-10-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20221007_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['create_date']},
        ),
    ]
