# Generated by Django 3.2.15 on 2022-10-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/media/blog/defult.jpg', upload_to='blog/'),
        ),
    ]
