# Generated by Django 3.2.15 on 2022-10-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='named',
            new_name='name',
        ),
    ]
